name: "Grafana Energy Manager"
slug: grafana-energymanager
version: "0.1.0"
description: "Custom Grafana addon with Energy Manager dashboards"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:chart-line
ports:
  3000/tcp: 3000
map:
  - config:rw
  - share:rw
